### ISSUE TITLE
Zend Expressive Middleware

### ISSUE THREAD

**Issue by reinfi** [goaop/goaop-zf2-module#10]
Hey @lisachenko,

I created a zend expressive middleware for goaop.

https://github.com/reinfi/goaop-zend-expressive-middleware

If you would like to have this under the goaop name, just let me know.
If not, I'm fine too :-)

PS: Did not know how to contact you otherwise than an issue.

**Comment by lisachenko** [comment]
Hi, @reinfi! Great job ) Thank you for your work, it's always pleasant to see one more integration with my framework and appreciate each contribution.

So, if you don't mind, let's move your library under `goaop` organization and you will get full admin access to this repo. Keeping integration modules under one single organization is good, because everyone could discover plugin for his own framework easily.

PS. You could always contact me via twitter `@lisachenko` or via email in my profile.

**Comment by reinfi** [comment]
I don't know how to move a repository, but feel free to copy the code and add it to your repository. I will then delete my repository.

**Comment by lisachenko** [comment]
@reinfi Please, open `Settings` => `Danger Zone` => `Transfer ownership` and put `goaop` as a receiver.
After that it should appear in `goaop` vendor and I will grant you all privileges on it.

**Comment by reinfi** [comment]
@lisachenko Tried to, but then comes `You don’t have the permission to create repositories on goaop `.

**Comment by reinfi** [comment]
Deleted my repository :)

**Comment by lisachenko** [comment]
Looks like it is still the best way to fork project, because repo transferring works good only if someone is admin in both repos.

**Comment by lisachenko** [comment]
Moved to [goaop/goaop-zend-expressive-middleware](https://github.com/goaop/goaop-zend-expressive-middleware)
